## Training Naive Bayes Model

In [1]:
from sklearn.naive_bayes import GaussianNB
from tqdm import tqdm

In [2]:
%run "../Get Features.ipynb"

In [5]:
import numpy as np

In [6]:
%%time
a = get_all()
a = [np.hstack(i) for i in a]
pronoun, verbs, entity_counts, sen_len, sen_pos, stop_counts, output = a

loaded tags
loaded doc metadata
loaded stop counts
loaded outputs
CPU times: user 2min 19s, sys: 40.9 s, total: 3min
Wall time: 4min 50s


In [7]:
x = []

def get_fvect(i):
    fvect = [pronoun[i], verbs[i], entity_counts[i], sen_len[i], sen_pos[i], stop_counts[i]]

    return np.asarray(fvect)
    
for i in tqdm(range(len(pronoun))):
    x.append(get_fvect(i))

100%|██████████| 7559250/7559250 [00:44<00:00, 170904.96it/s]


In [8]:
x = np.asarray(x)

In [9]:
y = np.asarray(output)

In [10]:
bayes_clsf = GaussianNB()
bayes_clsf.fit(x, y)

GaussianNB(priors=None)

In [11]:
bayes_clsf.predict([[ 3,  2,  1, 17, 11,  8]])

array([0])

In [12]:
bayes_clsf.theta_

array([[  1.34263311,   2.75037769,   0.97571239,  19.31056766,
         21.84443449,   8.55280738],
       [  1.65492704,   4.10690546,   2.67279624,  32.70667046,
         14.32934332,  12.63740534],
       [  1.42011271,   3.22876426,   1.57733797,  23.98790809,
         17.80195719,   9.9989353 ]])

In [13]:
bayes_clsf.sigma_

array([[   1.83475972,    3.51395267,    2.26251264,  116.55232012,
         207.37672246,   23.5682712 ],
       [   2.98482622,    8.51124486,    9.36077274,  438.24841698,
         178.52283444,   63.66841889],
       [   2.08999781,    4.46458595,    3.52514001,  166.35604399,
         178.19108311,   30.16031335]])

## Testing Model

In [14]:
a = get_all(type_=2)

loaded tags
loaded doc metadata
loaded stop counts
loaded outputs


In [15]:
testx = []

a = [np.hstack(i) for i in a]
pronoun, verbs, entity_counts, sen_len, sen_pos, stop_counts, output = a

for i in tqdm(range(len(pronoun))):
    testx.append(get_fvect(i))

100%|██████████| 359844/359844 [00:02<00:00, 161398.62it/s]


In [16]:
testx = np.asarray(testx)
testy = np.asarray(output)

In [17]:
pred = bayes_clsf.predict(testx)

In [18]:
pred.shape

(359844,)

In [19]:
testy.shape

(359844,)

## Accuracy

In [20]:
accuracy = 0
for i in range(len(pred)):
    if pred[i] == testy[i]:
        accuracy += 1

print(accuracy/pred.shape[0])

0.5156817954446927


## Sample output for a document

In [21]:
%run ../paths.py

In [22]:
text = open(TEXT_FOLDER + 'test/doc.1.txt').readlines()

In [23]:
features = get_all(start=1, end=2, type_=2)

loaded tags
loaded doc metadata
loaded stop counts
loaded outputs


## Sample Document

In [24]:
for i in text:
    print(i)

traitor @entity0 has revealed he did not read all the top - secret intelligence documents he leaked – a move which put lives at risk from terrorists

in a television interview the fugitive squirmed as he admitted only ‘ evaluating ’ the files stolen from @entity10 and the @entity11

the former @entity13 spy also acknowledged there had been a ‘ f * * * - up ’ when newspapers that were handed the classified material failed to redact sensitive details exposing operations against @entity19

the 31 - year - old stunned the world in june 2013 – less than a month after the murder of @entity35 by @entity37 extremists – when he broke cover as the civilian @entity40 worker who stole classified documents

he leaked information about attempts by spying agencies including @entity10 and the @entity11 to view citizens ’ private information , claiming internet history , emails , text messages , calls and passwords were harvested

but security chiefs have warned that secret techniques , revealed by @en

In [25]:
bayes_clsf.class_count_

array([ 3134808.,  2912274.,  1512168.])

In [26]:
bayes_clsf.class_prior_

array([ 0.41469828,  0.38525965,  0.20004207])

In [28]:
bayes_clsf.theta_

array([[  1.34263311,   2.75037769,   0.97571239,  19.31056766,
         21.84443449,   8.55280738],
       [  1.65492704,   4.10690546,   2.67279624,  32.70667046,
         14.32934332,  12.63740534],
       [  1.42011271,   3.22876426,   1.57733797,  23.98790809,
         17.80195719,   9.9989353 ]])

In [29]:
bayes_clsf.sigma_

array([[   1.83475972,    3.51395267,    2.26251264,  116.55232012,
         207.37672246,   23.5682712 ],
       [   2.98482622,    8.51124486,    9.36077274,  438.24841698,
         178.52283444,   63.66841889],
       [   2.08999781,    4.46458595,    3.52514001,  166.35604399,
         178.19108311,   30.16031335]])